#!/usr/bin/env python3

from rucio.client import Client

client = Client()

SDSC = {
    "hostname": "xrootd-sense-redirector-111.sdsc.optiputer.net",
    "scheme": "davs",
    "port": 1094,
    "prefix": "//",
    "impl": "rucio.rse.protocols.gfal.Default",
    "domains": {
        "lan": {
            "read": 1,
            "write": 1,
            "delete": 1
        },
        "wan": {
            "read": 1,
            "write": 1,
            "delete": 1,
            "third_party_copy_read": 1,
            "third_party_copy_write": 1
        }
    }
}

CALTECH = {
    "hostname": "sense-redir-01.ultralight.org",
    "scheme": "davs",
    "port": 1094,
    "prefix": "//store/temp",
    "impl": "rucio.rse.protocols.gfal.Default",
    "domains": {
        "lan": {
            "read": 1,
            "write": 1,
            "delete": 1
        },
        "wan": {
            "read": 1,
            "write": 1,
            "delete": 1,
            "third_party_copy_read": 1,
            "third_party_copy_write": 1
        }
    }
}

FERMILAB = {
    "hostname": "cmssense4-origin-2841-1.fnal.gov",
    "scheme": "davs",
    "port": 2880,
    "prefix": "//dcache/store/temp",
    "impl": "rucio.rse.protocols.gfal.Default",
    "domains": {
        "lan": {
            "read": 1,
            "write": 1,
            "delete": 1
        },
        "wan": {
            "read": 1,
            "write": 1,
            "delete": 1,
            "third_party_copy_read": 1,
            "third_party_copy_write": 1
        }
    }
}

client.add_rse("T2_US_SDSC")
client.add_rse("T2_US_Caltech_Test")
client.add_rse("T1_US_FNAL")

client.add_protocol("T2_US_SDSC", SDSC)
client.add_protocol("T2_US_Caltech_Test", CALTECH)
client.add_protocol("T1_US_FNAL", FERMILAB)

client.add_distance("T2_US_SDSC", "T2_US_Caltech_Test", {"ranking":1,"distance":1})
client.add_distance("T2_US_SDSC", "T1_US_FNAL", {"ranking":1,"distance":1})
client.add_distance("T2_US_Caltech_Test", "T2_US_SDSC", {"ranking":1,"distance":1})
client.add_distance("T2_US_Caltech_Test", "T1_US_FNAL", {"ranking":1,"distance":1})
client.add_distance("T1_US_FNAL", "T2_US_SDSC", {"ranking":1,"distance":1})
client.add_distance("T1_US_FNAL", "T2_US_Caltech_Test", {"ranking":1,"distance":1})

client.set_local_account_limit("root", "T2_US_SDSC", "-1" )
client.set_local_account_limit("root", "T2_US_Caltech_Test", "-1" )
client.set_local_account_limit("root", "T1_US_FNAL", "-1" )

client.add_rse_attribute("T2_US_SDSC", "fts", "https://fts3-pilot.cern.ch:8446")
client.add_rse_attribute("T2_US_Caltech_Test", "fts", "https://fts3-pilot.cern.ch:8446")
client.add_rse_attribute("T1_US_FNAL", "fts", "https://fts3-pilot.cern.ch:8446")

client.add_rse_attribute("T2_US_SDSC", "lfn2pfn_algorithm", "cmstfc")
client.add_rse_attribute("T2_US_Caltech_Test", "lfn2pfn_algorithm", "cmstfc")
client.add_rse_attribute("T1_US_FNAL", "lfn2pfn_algorithm", "cmstfc")

client.add_scope("root", "cms")
